bin/main.ml
lib/gtype.ml
lib/gtype.mli
lib/lib.ml
lib/ltype.ml
lib/ltype.mli

In passing, I have renamed some types and function to make them sorter
and clearer.

Mli files for gtype/ltype.

---

lib/lib.ml

First step towards merging the web interface.
For the web interface, we need to parse strings and not input_channels or files.

Lib: implement parse_from_string.

---

lib/lib.mli

Documentation for the Lib module.
Please have a look at the description of the function.

Documentation for Lib.

---

lib/ltype.ml

Check payload before merging receives

---

web/index.html
web/interface.ml
web/live.ml

Preview available: https://www.doc.ic.ac.uk/~fz315/nuscr

Visualise fsm

---

web/Makefile
web/index.html
web/style.css

Add logo and GitHub link

---

lib/err.ml
lib/gtype.ml
lib/ltype.ml
lib/protocol.ml
test/test.ml

Closes #58 #57 
To discuss: new test failures due to Scribble not requiring consistent choices, what do we do?

Error messages

---

CHANGES.md
Readme.md
dune-project
nuscr.opam

- Add CHANGES.md, required for opam (currently empty, will fill out later)
- Add description in dune-project

Project settings

---

CHANGES.md
bin/main.ml
lib/lib.ml
lib/lib.mli
web/live.ml

Lib signature changes

---

CHANGES.md
bin/dune
dune-project
nuscr-web.opam

Make web a separate package

---

utils/authors.sh

Useful when releasing new versions

Add a script to update authors

---

CHANGES.md
bin/main.ml
examples/parser/pragma/calc.scr
lib/err.ml
lib/lexer.mll
lib/lib.ml
lib/lib.mli
lib/parser.mly
lib/syntax.ml

Added support for Pragmas

---

CHANGES.md
examples/parser/pragma/calc.scr
lib/parser.mly
test/test.ml

Pragma fix

---

lib/gtype.ml
lib/parser.mly
lib/syntax.ml

Remove qnames

---

CHANGES.md
examples/errors/unboundrec.scr
lib/gtype.ml

Remove degenerate recursion in global types

---

.circleci/config.yml
.dockerignore
Dockerfile

Add a Dockerfile and CI docker image building

---

CHANGES.md
bin/dune
bin/main.ml
dune-project
nuscr.opam

Closes #90
Closes #88 
Closes #77 
Closes #74

New cmdliner-based command line interface

---

bin/main.ml
lib/lib.ml
lib/lib.mli
lib/loc.ml
lib/syntax.ml

added the option to print a s-expression

---

.circleci/config.yml
.dockerignore
Dockerfile

So that the docker image contains version and url to report issues

Run dune subst before building docker image

---

lib/gocodegen.ml
lib/gocodegen.mli
lib/goenvs.ml
lib/goenvs.mli
lib/gtype.ml
lib/gtype.mli
lib/ltype.ml
lib/ltype.mli
lib/namegen.ml
lib/symtable.ml

https://ocaml.janestreet.com/ocaml-core/latest/doc/base/Base/Map/M/index.html

Replace Map.t uses, use Map.M(...).t instead

---

lib/fsutil.ml
lib/gocodegen.ml
lib/gocodegen.mli
lib/gtype.ml
lib/gtype.mli
lib/lib.ml

Move some Go codegen out of lib.ml

Refactor Go Codegen

---

lib/lib.ml
lib/lib.mli

added an API function to get global protocols

---

dune-project
nuscr.opam
test/cram-tests/dune

Fixes issues detected in https://github.com/nuscr/nuscr/pull/140

Fix the tests and add missing test dependency
